// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with [Firebase.initializeApp].
///
/// To connect to your specific Firebase project, please run:
/// ```bash
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder configurations for web, android, and ios.
  // Replace these by running `flutterfire configure` or filling in your actual keys.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-apiKey-web-carbonaware',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'carbonaware-placeholder',
    authDomain: 'carbonaware-placeholder.firebaseapp.com',
    storageBucket: 'carbonaware-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-apiKey-android-carbonaware',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'carbonaware-placeholder',
    storageBucket: 'carbonaware-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-apiKey-ios-carbonaware',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'carbonaware-placeholder',
    storageBucket: 'carbonaware-placeholder.appspot.com',
    iosBundleId: 'com.example.carbonAware',
  );
}
