// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with [Firebase.initializeApp].
///
/// To connect to your specific Firebase project, please run:
/// ```bash
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder configurations for web, android, and ios.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwlEsCTs3NlMglP2QqHjcwiyvhGGy7XuY',
    appId: '1:1017440772168:web:b7e5f09b69b9a731dbb87d',
    messagingSenderId: '1017440772168',
    projectId: 'carbonaware-500117',
    authDomain: 'carbonaware-500117.firebaseapp.com',
    storageBucket: 'carbonaware-500117.firebasestorage.app',
    measurementId: 'G-N4Z87CLR0G',
  );

  // Replace these by running `flutterfire configure` or filling in your actual keys.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPxYG5p3GWLmhoO7NDcJ3Wv0kmjDFqVE',
    appId: '1:1017440772168:android:4fd24dea78f0698adbb87d',
    messagingSenderId: '1017440772168',
    projectId: 'carbonaware-500117',
    storageBucket: 'carbonaware-500117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoBbjyV8xwJ9-8cN28JmLzuES-1VTbEwA',
    appId: '1:1017440772168:ios:fd8acbadea8830e7dbb87d',
    messagingSenderId: '1017440772168',
    projectId: 'carbonaware-500117',
    storageBucket: 'carbonaware-500117.firebasestorage.app',
    iosClientId: '1017440772168-knsorslil1el1lpukvn3rn7dnosccq9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.carbonAware',
  );

}